### ISSUE TITLE
pulsate sdk in swift 2.1

### ISSUE THREAD

**Issue by galu08** [PulsateHQ/pulsate-ios-sdk#1]
Hi, I want to install the Pulsate SDK into my project. I follow your instructions in this link: https://pulsate.readme.io/docs/installing-the-pulsate-sdk , but when I run the app I got this message in the console and the app crash:

-[PULPulsateManager initWithDependency:andAccessToken:withLocationEnabled:andPushEnabled:error:]: unrecognized selector sent to instance 0x12f59a9e0
2015-11-12 11:38:27.710 MyAPP[9423:4785179] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PULPulsateManager initWithDependency:andAccessToken:withLocationEnabled:andPushEnabled:error:]: unrecognized selector sent to instance 0x12f59a9e0'
**\* First throw call stack:
(0x18458cf48 0x199a37f80 0x184593c5c 0x184590c00 0x184494cac 0x1000fdedc 0x1000fdbf8 0x1000fdfc8 0x1000a96f4 0x1000a9e8c 0x189b95324 0x189dc3acc 0x189dc7e0c 0x189dc4f50 0x18e6f37c4 0x18e6f3b44 0x184544544 0x184543fd8 0x184541cd8 0x184470ca0 0x189b8e1c8 0x189b88ffc 0x1000aa7bc 0x19a27a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

In my appDelegate I have this:

``` swift
import PULPulsate

var pulsateManager: PULPulsateManager?

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    let pulsate_APP_ID = "123456"
    let pulsate_APP_KEY = "123456"
    do {
        let authData = try PULAuthorizationData(appId: pulsate_APP_ID, andAppKey: pulsate_APP_KEY)
        pulsateManager = try PULPulsateFactory.getInstanceWithAuthorizationData(authData, withLocationEnabled: true, withPushEnabled: true, withLaunchOptions: launchOptions)
        pulsateManager?.startPulsateSession()

    } catch _ {
             print("PULAuthorizationData fail")
         }
}
```

I think that the error is because in swift "launchOptions" is optional ( **[NSObject: AnyObject]?**), and PULPulsateFactory.getInstanceWithAuthorizationData: withLocationEnabled: withPushEnabled: withLaunchOptions needs that the parameter launchOptions be **[NSObject : AnyObject]!**

I try to cast [NSObject: AnyObject]? to NSDictionary, or if launchOptions == nil use an empty [NSObject: AnyObject](). But nothing works.

**Comment by michalciurus** [comment]
It looks like you're missing the -ObjC flag in your project settings.

You need to add -ObjC linker flag to project linker configuration. To do this, go to Build Settings tab of project settings, then to the Linking section and the flag to Other Linker Flags row, they are needed to load Pulsate (or any other library) category files properly.

If you're using CocoaPods it should do it automatically for you, unless you've overridden it in the settings.
If you've integrated PULPulsate manually, you have to add the -ObjC flag yourself.

**Comment by galu08** [comment]
YES!. that was the problem!. Thanks you so much!.
