### ISSUE TITLE
Issue with App Delegate Callbacks

### ISSUE THREAD

**Issue by MikeMcNamara** [PulsateHQ/pulsate-ios-sdk#3]
Hi, 

Just updated to release 2.8.5. After doing so, it appears that `applicationDidBecomeActive` isn't being hit in my App Delegate. 

From the documentation: 

```
Pulsate SDK sets a new delegate for UIApplication so it can do all the heavy lifting for you.
You will receive all UIApplicationDelegate callbacks, as they are forwarded to the original AppDelegate.

Remember to not to change the delegate property of UIApplication after instantiating Pulsate.
```

I retested the old SDK I was using (2.5.0) and the callback happened correctly. I also tested by not creating and starting a Pulsate session in didFinishLaunchingWithOptions. This also appeared to fix the issue.  

I would appreciate it if you could investigate this. Thank you.

**Comment by m1entus** [comment]
Could you check 2.8.6, this should probably be fixed ?
